/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOBUFF_PB_H_INCLUDED
#define PB_PROTOBUFF_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* mock enums — update when airbrake FSW is finalized */
typedef enum _FswStatus
{
    FswStatus_FSW_STATUS_UNKNOWN = 0,
    FswStatus_FSW_STATUS_IDLE = 1,
    FswStatus_FSW_STATUS_ACTIVE = 2
} FswStatus;

typedef enum _RocketState
{
    RocketState_ROCKET_STATE_UNKNOWN = 0,
    RocketState_ROCKET_STATE_IDLE = 1,
    RocketState_ROCKET_STATE_POWERED_FLIGHT = 2,
    RocketState_ROCKET_STATE_COAST = 3,
    RocketState_ROCKET_STATE_APOGEE = 4,
    RocketState_ROCKET_STATE_DESCENT = 5,
    RocketState_ROCKET_STATE_LANDED = 6
} RocketState;

typedef enum _AirbrakeStatus
{
    AirbrakeStatus_AIRBRAKE_STATUS_UNKNOWN = 0,
    AirbrakeStatus_AIRBRAKE_STATUS_RETRACTED = 1,
    AirbrakeStatus_AIRBRAKE_STATUS_DEPLOYED = 2
} AirbrakeStatus;

/* Struct definitions */
typedef struct _StatusData
{
    FswStatus fsw_status;
    RocketState rocket_state;
    AirbrakeStatus airbrake_status;
} StatusData;

typedef struct _IMUData
{
    float accel_x;
    float accel_y;
    float accel_z;
    float gyro_x;
    float gyro_y;
    float gyro_z;
    float quat_x;
    float quat_y;
    float quat_z;
    float linear_accel_x;
    float linear_accel_y;
    float linear_accel_z;
} IMUData;

typedef struct _BaroData
{
    float air_pressure; /* Pascals */
    float altitude;     /* Meters */
} BaroData;

typedef struct _RocketMessage
{
    bool has_status;
    StatusData status;
    bool has_imu;
    IMUData imu;
    bool has_baro;
    BaroData baro;
    uint32_t timestamp_us;
} RocketMessage;

#ifdef __cplusplus
extern "C"
{
#endif

/* Helper constants for enums */
#define _FswStatus_MIN FswStatus_FSW_STATUS_UNKNOWN
#define _FswStatus_MAX FswStatus_FSW_STATUS_ACTIVE
#define _FswStatus_ARRAYSIZE ((FswStatus)(FswStatus_FSW_STATUS_ACTIVE + 1))

#define _RocketState_MIN RocketState_ROCKET_STATE_UNKNOWN
#define _RocketState_MAX RocketState_ROCKET_STATE_LANDED
#define _RocketState_ARRAYSIZE \
    ((RocketState)(RocketState_ROCKET_STATE_LANDED + 1))

#define _AirbrakeStatus_MIN AirbrakeStatus_AIRBRAKE_STATUS_UNKNOWN
#define _AirbrakeStatus_MAX AirbrakeStatus_AIRBRAKE_STATUS_DEPLOYED
#define _AirbrakeStatus_ARRAYSIZE \
    ((AirbrakeStatus)(AirbrakeStatus_AIRBRAKE_STATUS_DEPLOYED + 1))

#define StatusData_fsw_status_ENUMTYPE FswStatus
#define StatusData_rocket_state_ENUMTYPE RocketState
#define StatusData_airbrake_status_ENUMTYPE AirbrakeStatus

/* Initializer values for message structs */
#define StatusData_init_default \
    {_FswStatus_MIN, _RocketState_MIN, _AirbrakeStatus_MIN}
#define IMUData_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BaroData_init_default {0, 0}
#define RocketMessage_init_default                                \
    {false, StatusData_init_default, false, IMUData_init_default, \
     false, BaroData_init_default,   0}
#define StatusData_init_zero \
    {_FswStatus_MIN, _RocketState_MIN, _AirbrakeStatus_MIN}
#define IMUData_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BaroData_init_zero {0, 0}
#define RocketMessage_init_zero                             \
    {false, StatusData_init_zero, false, IMUData_init_zero, \
     false, BaroData_init_zero,   0}

/* Field tags (for use in manual encoding/decoding) */
#define StatusData_fsw_status_tag 1
#define StatusData_rocket_state_tag 2
#define StatusData_airbrake_status_tag 3
#define IMUData_accel_x_tag 1
#define IMUData_accel_y_tag 2
#define IMUData_accel_z_tag 3
#define IMUData_gyro_x_tag 4
#define IMUData_gyro_y_tag 5
#define IMUData_gyro_z_tag 6
#define IMUData_quat_x_tag 7
#define IMUData_quat_y_tag 8
#define IMUData_quat_z_tag 9
#define IMUData_linear_accel_x_tag 10
#define IMUData_linear_accel_y_tag 11
#define IMUData_linear_accel_z_tag 12
#define BaroData_air_pressure_tag 1
#define BaroData_altitude_tag 2
#define RocketMessage_status_tag 1
#define RocketMessage_imu_tag 2
#define RocketMessage_baro_tag 3
#define RocketMessage_timestamp_us_tag 4

/* Struct field encoding specification for nanopb */
#define StatusData_FIELDLIST(X, a)                 \
    X(a, STATIC, SINGULAR, UENUM, fsw_status, 1)   \
    X(a, STATIC, SINGULAR, UENUM, rocket_state, 2) \
    X(a, STATIC, SINGULAR, UENUM, airbrake_status, 3)
#define StatusData_CALLBACK NULL
#define StatusData_DEFAULT NULL

#define IMUData_FIELDLIST(X, a)                       \
    X(a, STATIC, SINGULAR, FLOAT, accel_x, 1)         \
    X(a, STATIC, SINGULAR, FLOAT, accel_y, 2)         \
    X(a, STATIC, SINGULAR, FLOAT, accel_z, 3)         \
    X(a, STATIC, SINGULAR, FLOAT, gyro_x, 4)          \
    X(a, STATIC, SINGULAR, FLOAT, gyro_y, 5)          \
    X(a, STATIC, SINGULAR, FLOAT, gyro_z, 6)          \
    X(a, STATIC, SINGULAR, FLOAT, quat_x, 7)          \
    X(a, STATIC, SINGULAR, FLOAT, quat_y, 8)          \
    X(a, STATIC, SINGULAR, FLOAT, quat_z, 9)          \
    X(a, STATIC, SINGULAR, FLOAT, linear_accel_x, 10) \
    X(a, STATIC, SINGULAR, FLOAT, linear_accel_y, 11) \
    X(a, STATIC, SINGULAR, FLOAT, linear_accel_z, 12)
#define IMUData_CALLBACK NULL
#define IMUData_DEFAULT NULL

#define BaroData_FIELDLIST(X, a)                   \
    X(a, STATIC, SINGULAR, FLOAT, air_pressure, 1) \
    X(a, STATIC, SINGULAR, FLOAT, altitude, 2)
#define BaroData_CALLBACK NULL
#define BaroData_DEFAULT NULL

#define RocketMessage_FIELDLIST(X, a)          \
    X(a, STATIC, OPTIONAL, MESSAGE, status, 1) \
    X(a, STATIC, OPTIONAL, MESSAGE, imu, 2)    \
    X(a, STATIC, OPTIONAL, MESSAGE, baro, 3)   \
    X(a, STATIC, SINGULAR, UINT32, timestamp_us, 4)
#define RocketMessage_CALLBACK NULL
#define RocketMessage_DEFAULT NULL
#define RocketMessage_status_MSGTYPE StatusData
#define RocketMessage_imu_MSGTYPE IMUData
#define RocketMessage_baro_MSGTYPE BaroData

    extern const pb_msgdesc_t StatusData_msg;
    extern const pb_msgdesc_t IMUData_msg;
    extern const pb_msgdesc_t BaroData_msg;
    extern const pb_msgdesc_t RocketMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define StatusData_fields &StatusData_msg
#define IMUData_fields &IMUData_msg
#define BaroData_fields &BaroData_msg
#define RocketMessage_fields &RocketMessage_msg

/* Maximum encoded size of messages (where known) */
#define BaroData_size 10
#define IMUData_size 60
#define PROTOBUFF_PB_H_MAX_SIZE RocketMessage_size
#define RocketMessage_size 88
#define StatusData_size 6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
