/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "protobuff.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, AUTO)

PB_BIND(IMUData, IMUData, AUTO)

PB_BIND(BaroData, BaroData, AUTO)

PB_BIND(RocketMessage, RocketMessage, AUTO)
