/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_PROTOBUFF_PB_H_INCLUDED
#define PB_PROTOBUFF_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Header
{
    uint32_t device_id;
    uint32_t packet_count;
    uint32_t timestamp_ms;
} Header;

typedef struct _IMUData
{
    float accel_x;
    float accel_y;
    float accel_z;
    float gyro_x;
    float gyro_y;
    float gyro_z;
    float quat_w;
    float quat_x;
    float quat_y;
    float quat_z;
} IMUData;

typedef struct _BaroData
{
    float pressure;
    float temperature;
} BaroData;

typedef struct _RocketMessage
{
    bool has_header;
    Header header;
    bool has_imu;
    IMUData imu;
    bool has_baro;
    BaroData baro;
} RocketMessage;

#ifdef __cplusplus
extern "C"
{
#endif

/* Initializer values for message structs */
#define Header_init_default {0, 0, 0}
#define IMUData_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BaroData_init_default {0, 0}
#define RocketMessage_init_default                             \
    {false, Header_init_default,  false, IMUData_init_default, \
     false, BaroData_init_default}
#define Header_init_zero {0, 0, 0}
#define IMUData_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BaroData_init_zero {0, 0}
#define RocketMessage_init_zero                          \
    {false, Header_init_zero,  false, IMUData_init_zero, \
     false, BaroData_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define Header_device_id_tag 1
#define Header_packet_count_tag 2
#define Header_timestamp_ms_tag 3
#define IMUData_accel_x_tag 1
#define IMUData_accel_y_tag 2
#define IMUData_accel_z_tag 3
#define IMUData_gyro_x_tag 4
#define IMUData_gyro_y_tag 5
#define IMUData_gyro_z_tag 6
#define IMUData_quat_w_tag 7
#define IMUData_quat_x_tag 8
#define IMUData_quat_y_tag 9
#define IMUData_quat_z_tag 10
#define BaroData_pressure_tag 1
#define BaroData_temperature_tag 2
#define RocketMessage_header_tag 1
#define RocketMessage_imu_tag 2
#define RocketMessage_baro_tag 3

/* Struct field encoding specification for nanopb */
#define Header_FIELDLIST(X, a)                      \
    X(a, STATIC, SINGULAR, UINT32, device_id, 1)    \
    X(a, STATIC, SINGULAR, UINT32, packet_count, 2) \
    X(a, STATIC, SINGULAR, UINT32, timestamp_ms, 3)
#define Header_CALLBACK NULL
#define Header_DEFAULT NULL

#define IMUData_FIELDLIST(X, a)               \
    X(a, STATIC, SINGULAR, FLOAT, accel_x, 1) \
    X(a, STATIC, SINGULAR, FLOAT, accel_y, 2) \
    X(a, STATIC, SINGULAR, FLOAT, accel_z, 3) \
    X(a, STATIC, SINGULAR, FLOAT, gyro_x, 4)  \
    X(a, STATIC, SINGULAR, FLOAT, gyro_y, 5)  \
    X(a, STATIC, SINGULAR, FLOAT, gyro_z, 6)  \
    X(a, STATIC, SINGULAR, FLOAT, quat_w, 7)  \
    X(a, STATIC, SINGULAR, FLOAT, quat_x, 8)  \
    X(a, STATIC, SINGULAR, FLOAT, quat_y, 9)  \
    X(a, STATIC, SINGULAR, FLOAT, quat_z, 10)
#define IMUData_CALLBACK NULL
#define IMUData_DEFAULT NULL

#define BaroData_FIELDLIST(X, a)               \
    X(a, STATIC, SINGULAR, FLOAT, pressure, 1) \
    X(a, STATIC, SINGULAR, FLOAT, temperature, 2)
#define BaroData_CALLBACK NULL
#define BaroData_DEFAULT NULL

#define RocketMessage_FIELDLIST(X, a)          \
    X(a, STATIC, OPTIONAL, MESSAGE, header, 1) \
    X(a, STATIC, OPTIONAL, MESSAGE, imu, 2)    \
    X(a, STATIC, OPTIONAL, MESSAGE, baro, 3)
#define RocketMessage_CALLBACK NULL
#define RocketMessage_DEFAULT NULL
#define RocketMessage_header_MSGTYPE Header
#define RocketMessage_imu_MSGTYPE IMUData
#define RocketMessage_baro_MSGTYPE BaroData

    extern const pb_msgdesc_t Header_msg;
    extern const pb_msgdesc_t IMUData_msg;
    extern const pb_msgdesc_t BaroData_msg;
    extern const pb_msgdesc_t RocketMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Header_fields &Header_msg
#define IMUData_fields &IMUData_msg
#define BaroData_fields &BaroData_msg
#define RocketMessage_fields &RocketMessage_msg

/* Maximum encoded size of messages (where known) */
#define BaroData_size 10
#define Header_size 18
#define IMUData_size 50
#define PROTOBUFF_PB_H_MAX_SIZE RocketMessage_size
#define RocketMessage_size 84

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
