/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "protobuff.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(RocketStructProto, RocketStructProto, AUTO)

PB_BIND(Rockets, Rockets, AUTO)
